# Используем легкий Python-образ
FROM python:3.11-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем все файлы проекта
COPY . /app

# Обновляем pip и устанавливаем зависимости
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Чтобы Python выводил логи сразу, без буфера
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8

# Команда для запуска бота
CMD ["python", "main_py"]
